"""End-to-end demo smoke test; creates a fresh sample and a real MP4.

Run against a local demo server with requirements-dev.txt installed.
"""
from playwright.sync_api import sync_playwright, expect
from pathlib import Path
import argparse, json, shutil, time

parser = argparse.ArgumentParser(description="Verify the running Deco demo in a real browser.")
parser.add_argument("--url", default="http://localhost:8000")
parser.add_argument("--output", type=Path, default=Path("/tmp/deco-browser-check"))
parser.add_argument("--chrome", default=shutil.which("google-chrome"))
args = parser.parse_args()
args.output.mkdir(parents=True, exist_ok=True)
base_url = args.url.rstrip("/")
with sync_playwright() as p:
    browser = p.chromium.launch(executable_path=args.chrome, headless=True, args=['--no-sandbox', '--enable-unsafe-swiftshader', '--use-angle=swiftshader'])
    page = browser.new_page(viewport={'width':1440, 'height':1000}, device_scale_factor=1)
    errors = []
    page.on('pageerror', lambda e: errors.append(str(e)))
    page.goto(base_url + "/editor")
    page.wait_for_timeout(1000)
    page.screenshot(path=args.output / "deco-landing.png", full_page=True)
    page.get_by_role('button', name='Explore the demo studio').click()
    expect(page.locator('.object-card')).to_have_count(6)
    page.wait_for_timeout(5000)
    first=page.locator('.object-card').first
    first.locator('[data-action=toggle-open]').first.click()
    first.locator('[data-field=position]').fill('0.25, 1.6, 0')
    first.locator('[data-field=rotation]').fill('0, 0, 0.1')
    first.locator('[data-action=save]').click()
    page.wait_for_timeout(500)
    expect(page.locator('.object-card').first.locator('[data-field=position]')).to_have_value('0.25, 1.60, 0.00')
    page.locator('.object-card').first.locator('[data-action=duplicate]').click()
    expect(page.locator('.object-card')).to_have_count(7)
    duplicate=page.locator('.object-card').last
    duplicate.locator('[data-action=toggle-open]').first.click()
    duplicate.locator('[data-action=delete]').click()
    expect(page.locator('.object-card')).to_have_count(6)
    print('PASS: edit position/rotation, duplicate, delete',flush=True)
    page.reload()
    expect(page.locator('#workspace')).to_be_visible()
    expect(page.locator('.object-card')).to_have_count(6)
    page.locator('.object-card').first.locator('[data-action=toggle-open]').first.click()
    expect(page.locator('.object-card').first.locator('[data-field=position]')).to_have_value('0.25, 1.60, 0.00')
    page.locator('.object-card').first.locator('[data-action=toggle-open]').first.click()
    print('PASS: project and transform restored after reload',flush=True)
    page.wait_for_timeout(4000)
    page.screenshot(path=args.output / "deco-workspace.png", full_page=True)
    page.get_by_role('button',name='Shots & export').click()
    expect(page.locator('.keyframe-row')).to_have_count(3)
    page.locator('#render-fps').fill('12')
    page.locator('#render-width').fill('640')
    page.locator('#render-height').fill('360')
    start=time.monotonic()
    page.locator('#render-button').click()
    expect(page.locator('#render-button')).to_have_text('Rendering…')
    expect(page.locator('#render-library a')).to_have_count(1, timeout=180000)
    href=page.locator('#render-library a').get_attribute('href')
    response=page.request.get(base_url + href)
    assert response.status == 200 and len(response.body())>10000
    Path(args.output / "deco-demo.mp4").write_bytes(response.body())
    print(f'PASS: real browser MP4 export and download ({len(response.body())} bytes, {time.monotonic()-start:.1f}s)',flush=True)
    page.screenshot(path=args.output / "deco-render.png", full_page=True)
    page.reload()
    expect(page.locator('#render-library a')).to_have_count(1)
    page.wait_for_function("document.getElementById('render-video').readyState >= 2")
    page.locator('#render-video').evaluate("video => video.play()")
    page.wait_for_function("document.getElementById('render-video').currentTime > 0.2")
    print('PASS: render history restored and clip plays in the browser',flush=True)
    page.get_by_role('button',name='All spaces',exact=True).click()
    expect(page.locator('#landing')).to_be_visible()
    expect(page.locator('.project-card').first).to_be_visible()
    page.set_viewport_size({'width':390,'height':844})
    page.screenshot(path=args.output / "deco-mobile.png",full_page=True)
    assert page.evaluate('document.documentElement.scrollWidth <= innerWidth')
    print(json.dumps({'errors':errors,'status':page.locator('#status').inner_text()}),flush=True)
    assert not errors
    browser.close()
